CREATE PROCEDURE dbo.usp_User_Delete
	@MATK INT
AS
BEGIN
	SET NOCOUNT ON;
	DECLARE @t NVARCHAR(200);
	SELECT @t = TENDANGNHAP FROM TAIKHOAN WHERE MATK = @MATK;
	DELETE FROM TAIKHOAN WHERE MATK = @MATK;
	EXEC dbo.usp_AuditLog_Add 'UserDelete', @t, NULL, 'User deleted', @MATK, 'Success';
END
