CREATE PROCEDURE dbo.usp_User_Update
	@MATK INT,
	@MALOAITK INT,
	@TENCHU NVARCHAR(200),
	@TENDANGNHAP NVARCHAR(200),
	@MATKHAU NVARCHAR(MAX)
AS
BEGIN
	SET NOCOUNT ON;
	UPDATE TAIKHOAN
	SET MALOAITK = @MALOAITK,
		TENCHUTAIKHOAN = @TENCHU,
		TENDANGNHAP = @TENDANGNHAP,
		MATKHAU = @MATKHAU
	WHERE MATK = @MATK;
	EXEC dbo.usp_AuditLog_Add 'UserUpdate', @TENDANGNHAP, NULL, 'User updated', @MATK, 'Success';
END
