CREATE PROCEDURE dbo.usp_Role_Delete
	@MALOAITK INT
AS
BEGIN
	SET NOCOUNT ON;
	DECLARE @t NVARCHAR(200);
	SELECT @t = TENLOAITAIKHOAN FROM PHANLOAITAIKHOAN WHERE MALOAITK = @MALOAITK;
	DELETE FROM PHANLOAITAIKHOAN WHERE MALOAITK = @MALOAITK;
	EXEC dbo.usp_AuditLog_Add 'RoleDelete', NULL, @t, 'Role deleted', @MALOAITK, 'Success';
END
