CREATE PROCEDURE dbo.usp_Role_Create
	@TENLOAI NVARCHAR(200),
	@QUYEN NVARCHAR(MAX)
AS
BEGIN
	SET NOCOUNT ON;
	INSERT INTO PHANLOAITAIKHOAN(TENLOAITAIKHOAN, QUYENHAN) VALUES(@TENLOAI, @QUYEN);
	EXEC dbo.usp_AuditLog_Add 'RoleCreate', NULL, @TENLOAI, 'Role created', NULL, 'Success';
END
