CREATE PROCEDURE dbo.usp_User_Create
	@MALOAITK INT,
	@TENCHU NVARCHAR(200),
	@TENDANGNHAP NVARCHAR(200),
	@MATKHAU NVARCHAR(MAX)
AS
BEGIN
	SET NOCOUNT ON;
	INSERT INTO TAIKHOAN(MALOAITK, TENCHUTAIKHOAN, TENDANGNHAP, MATKHAU)
	VALUES(@MALOAITK, @TENCHU, @TENDANGNHAP, @MATKHAU);
	EXEC dbo.usp_AuditLog_Add 'UserCreate', @TENDANGNHAP, NULL, 'User created', NULL, 'Success';
END
