CREATE PROCEDURE dbo.usp_Role_Update
	@MALOAITK INT,
	@TENLOAI NVARCHAR(200),
	@QUYEN NVARCHAR(MAX)
AS
BEGIN
	SET NOCOUNT ON;
	UPDATE PHANLOAITAIKHOAN SET TENLOAITAIKHOAN = @TENLOAI, QUYENHAN = @QUYEN WHERE MALOAITK = @MALOAITK;
	EXEC dbo.usp_AuditLog_Add 'RoleUpdate', NULL, @TENLOAI, 'Role updated', @MALOAITK, 'Success';
END
