-- FINAL GRANTS SCRIPT: create app_role, app schema wrappers, grant execute, deny direct table DML
SET NOCOUNT ON;

-- configurable application database user name (change to real user before running)
DECLARE @appUser SYSNAME = N'app_user';
DECLARE @sql NVARCHAR(MAX);

-- Create database role for application
IF NOT EXISTS (SELECT 1 FROM sys.database_principals WHERE name = N'app_role')
BEGIN
	EXEC('CREATE ROLE [app_role];');
END

-- Create application schema
IF NOT EXISTS (SELECT 1 FROM sys.schemas WHERE name = N'app')
BEGIN
	EXEC('CREATE SCHEMA [app];');
END

-- Create app schema wrapper stored procedures that delegate to dbo implementations or access dbo tables
-- Get user by username
IF OBJECT_ID('app.usp_User_GetByUsername','P') IS NULL
BEGIN
	EXEC('CREATE PROCEDURE app.usp_User_GetByUsername @TENDANGNHAP NVARCHAR(200) AS BEGIN SET NOCOUNT ON; SELECT MATK, MALOAITK, TENCHUTAIKHOAN, TENDANGNHAP, MATKHAU, FailedLoginCount, LockoutUntil FROM dbo.TAIKHOAN WHERE TENDANGNHAP = @TENDANGNHAP; END');
END

-- Wrappers for user CRUD that call the dbo stored procs (if present) or directly perform actions
IF OBJECT_ID('app.usp_User_Create','P') IS NULL
BEGIN
	EXEC('CREATE PROCEDURE app.usp_User_Create @MALOAITK INT, @TENCHU NVARCHAR(200), @TENDANGNHAP NVARCHAR(200), @MATKHAU NVARCHAR(MAX) AS BEGIN SET NOCOUNT ON; EXEC dbo.usp_User_Create @MALOAITK=@MALOAITK, @TENCHU=@TENCHU, @TENDANGNHAP=@TENDANGNHAP, @MATKHAU=@MATKHAU; END');
END

IF OBJECT_ID('app.usp_User_Update','P') IS NULL
BEGIN
	EXEC('CREATE PROCEDURE app.usp_User_Update @MATK INT, @MALOAITK INT, @TENCHU NVARCHAR(200), @TENDANGNHAP NVARCHAR(200), @MATKHAU NVARCHAR(MAX) AS BEGIN SET NOCOUNT ON; EXEC dbo.usp_User_Update @MATK=@MATK, @MALOAITK=@MALOAITK, @TENCHU=@TENCHU, @TENDANGNHAP=@TENDANGNHAP, @MATKHAU=@MATKHAU; END');
END

IF OBJECT_ID('app.usp_User_Delete','P') IS NULL
BEGIN
	EXEC('CREATE PROCEDURE app.usp_User_Delete @MATK INT AS BEGIN SET NOCOUNT ON; EXEC dbo.usp_User_Delete @MATK=@MATK; END');
END

-- Role wrappers
IF OBJECT_ID('app.usp_Role_Create','P') IS NULL
BEGIN
	EXEC('CREATE PROCEDURE app.usp_Role_Create @TENLOAI NVARCHAR(200), @QUYEN NVARCHAR(MAX) AS BEGIN SET NOCOUNT ON; EXEC dbo.usp_Role_Create @TENLOAI=@TENLOAI, @QUYEN=@QUYEN; END');
END

IF OBJECT_ID('app.usp_Role_Update','P') IS NULL
BEGIN
	EXEC('CREATE PROCEDURE app.usp_Role_Update @MALOAITK INT, @TENLOAI NVARCHAR(200), @QUYEN NVARCHAR(MAX) AS BEGIN SET NOCOUNT ON; EXEC dbo.usp_Role_Update @MALOAITK=@MALOAITK, @TENLOAI=@TENLOAI, @QUYEN=@QUYEN; END');
END

IF OBJECT_ID('app.usp_Role_Delete','P') IS NULL
BEGIN
	EXEC('CREATE PROCEDURE app.usp_Role_Delete @MALOAITK INT AS BEGIN SET NOCOUNT ON; EXEC dbo.usp_Role_Delete @MALOAITK=@MALOAITK; END');
END

-- UserRole wrappers
IF OBJECT_ID('app.usp_UserRole_Assign','P') IS NULL
BEGIN
	EXEC('CREATE PROCEDURE app.usp_UserRole_Assign @MATK INT, @MALOAITK INT AS BEGIN SET NOCOUNT ON; EXEC dbo.usp_UserRole_Assign @MATK=@MATK, @MALOAITK=@MALOAITK; END');
END

IF OBJECT_ID('app.usp_UserRole_Revoke','P') IS NULL
BEGIN
	EXEC('CREATE PROCEDURE app.usp_UserRole_Revoke @MATK INT, @MALOAITK INT AS BEGIN SET NOCOUNT ON; EXEC dbo.usp_UserRole_Revoke @MATK=@MATK, @MALOAITK=@MALOAITK; END');
END

-- THAMSO access wrappers
IF OBJECT_ID('app.usp_ThamSo_Get','P') IS NULL
BEGIN
	EXEC('CREATE PROCEDURE app.usp_ThamSo_Get @MATHAMSO NVARCHAR(20) AS BEGIN SET NOCOUNT ON; SELECT GIATRI FROM dbo.THAMSO WHERE MATHAMSO = @MATHAMSO; END');
END

IF OBJECT_ID('app.usp_ThamSo_Update','P') IS NULL
BEGIN
	EXEC('CREATE PROCEDURE app.usp_ThamSo_Update @MATHAMSO NVARCHAR(20), @GIATRI NVARCHAR(200) AS BEGIN SET NOCOUNT ON; UPDATE dbo.THAMSO SET GIATRI = @GIATRI WHERE MATHAMSO = @MATHAMSO; EXEC dbo.usp_AuditLog_Add ''ParamUpdate'', NULL, @MATHAMSO, ''Parameter updated'', NULL, ''Success''; END');
END

-- Grant execute on all stored procedures to app_role
GRANT EXECUTE ON SCHEMA::dbo TO [app_role];
GRANT EXECUTE ON SCHEMA::app TO [app_role];

-- Deny direct table DML on dbo schema to app_role
DENY SELECT, INSERT, UPDATE, DELETE ON SCHEMA::dbo TO [app_role];

-- Create database user for application if not exists and add to role
IF NOT EXISTS (SELECT 1 FROM sys.database_principals WHERE name = @appUser)
BEGIN
	-- Create user mapped to same-named login; adjust as necessary
	SET @sql = N'IF NOT EXISTS (SELECT 1 FROM sys.server_principals WHERE name = N''' + @appUser + N''') BEGIN PRINT ''Server login does not exist: ' + @appUser + '''; END ELSE BEGIN CREATE USER [' + @appUser + N'] FOR LOGIN [' + @appUser + N']; END';
	EXEC(@sql);
END

-- Add to role
IF EXISTS (SELECT 1 FROM sys.database_principals WHERE name = @appUser)
BEGIN
	IF NOT EXISTS (SELECT 1 FROM sys.database_role_members rm JOIN sys.database_principals r ON rm.role_principal_id = r.principal_id JOIN sys.database_principals u ON rm.member_principal_id = u.principal_id WHERE r.name = 'app_role' AND u.name = @appUser)
	BEGIN
		EXEC('ALTER ROLE [app_role] ADD MEMBER [' + @appUser + ']');
	END

	-- Remove elevated perms: ensure not member of db_owner
	IF EXISTS (SELECT 1 FROM sys.database_role_members rm JOIN sys.database_principals r ON rm.role_principal_id = r.principal_id JOIN sys.database_principals u ON rm.member_principal_id = u.principal_id WHERE r.name = 'db_owner' AND u.name = @appUser)
	BEGIN
		EXEC('ALTER ROLE [db_owner] DROP MEMBER [' + @appUser + ']');
	END
END

PRINT 'GRANT script completed. Review @appUser variable at top and adjust as needed.';

-- Create stored procedures for main tables (dbo schema) to be used by application
-- BANGTINHLUONG
IF OBJECT_ID('dbo.usp_BangTinhLuong_Insert','P') IS NULL
EXEC('CREATE PROCEDURE dbo.usp_BangTinhLuong_Insert @MANV INT, @LUONG MONEY, @THANG INT, @NAM INT, @GHICHU NVARCHAR(80) AS BEGIN SET NOCOUNT ON; INSERT INTO dbo.BANGTINHLUONG(MANV,LUONG,THANG,NAM,GHICHU) VALUES(@MANV,@LUONG,@THANG,@NAM,@GHICHU); END');
IF OBJECT_ID('dbo.usp_BangTinhLuong_Update','P') IS NULL
EXEC('CREATE PROCEDURE dbo.usp_BangTinhLuong_Update @MANV INT, @LUONG MONEY, @THANG INT, @NAM INT, @GHICHU NVARCHAR(80) AS BEGIN SET NOCOUNT ON; UPDATE dbo.BANGTINHLUONG SET LUONG=@LUONG, GHICHU=@GHICHU WHERE MANV=@MANV AND THANG=@THANG AND NAM=@NAM; END');
IF OBJECT_ID('dbo.usp_BangTinhLuong_Delete','P') IS NULL
EXEC('CREATE PROCEDURE dbo.usp_BangTinhLuong_Delete @MANV INT, @THANG INT, @NAM INT AS BEGIN SET NOCOUNT ON; DELETE FROM dbo.BANGTINHLUONG WHERE MANV=@MANV AND THANG=@THANG AND NAM=@NAM; END');
IF OBJECT_ID('dbo.usp_BangTinhLuong_GetByMonthYear','P') IS NULL
EXEC('CREATE PROCEDURE dbo.usp_BangTinhLuong_GetByMonthYear @THANG INT = NULL, @NAM INT = NULL AS BEGIN SET NOCOUNT ON; IF @THANG IS NULL BEGIN SELECT * FROM dbo.BANGTINHLUONG WHERE NAM = @NAM; END ELSE BEGIN SELECT * FROM dbo.BANGTINHLUONG WHERE THANG = @THANG AND NAM = @NAM; END END');

-- BANGCHAMCONG
IF OBJECT_ID('dbo.usp_BangChamCong_Insert','P') IS NULL
EXEC('CREATE PROCEDURE dbo.usp_BangChamCong_Insert @MANV INT, @THANG INT, @NAM INT, @MALUONG NVARCHAR(8), @TIENKHENTHUONG MONEY, @TIENKYLUAT MONEY, @SONGAYCONG INT, @SONGAYNGHI INT, @SOGIOLAMTHEM INT, @GHICHU NVARCHAR(80) AS BEGIN SET NOCOUNT ON; INSERT INTO dbo.BANGCHAMCONG(MANV,THANG,NAM,MALUONG,TIENKHENTHUONG,TIENKYLUAT,SONGAYCONG,SONGAYNGHI,SOGIOLAMTHEM,GHICHU) VALUES(@MANV,@THANG,@NAM,@MALUONG,@TIENKHENTHUONG,@TIENKYLUAT,@SONGAYCONG,@SONGAYNGHI,@SOGIOLAMTHEM,@GHICHU); END');
IF OBJECT_ID('dbo.usp_BangChamCong_Update','P') IS NULL
EXEC('CREATE PROCEDURE dbo.usp_BangChamCong_Update @MANV INT, @THANG INT, @NAM INT, @MALUONG NVARCHAR(8), @TIENKHENTHUONG MONEY, @TIENKYLUAT MONEY, @SONGAYCONG INT, @SONGAYNGHI INT, @SOGIOLAMTHEM INT, @GHICHU NVARCHAR(80) AS BEGIN SET NOCOUNT ON; UPDATE dbo.BANGCHAMCONG SET MALUONG=@MALUONG, TIENKHENTHUONG=@TIENKHENTHUONG, TIENKYLUAT=@TIENKYLUAT, SONGAYCONG=@SONGAYCONG, SONGAYNGHI=@SONGAYNGHI, SOGIOLAMTHEM=@SOGIOLAMTHEM, GHICHU=@GHICHU WHERE MANV=@MANV AND THANG=@THANG AND NAM=@NAM; END');
IF OBJECT_ID('dbo.usp_BangChamCong_Delete','P') IS NULL
EXEC('CREATE PROCEDURE dbo.usp_BangChamCong_Delete @MANV INT, @THANG INT, @NAM INT AS BEGIN SET NOCOUNT ON; DELETE FROM dbo.BANGCHAMCONG WHERE MANV=@MANV AND THANG=@THANG AND NAM=@NAM; END');
IF OBJECT_ID('dbo.usp_BangChamCong_GetByManvMonthYear','P') IS NULL
EXEC('CREATE PROCEDURE dbo.usp_BangChamCong_GetByManvMonthYear @MANV INT, @THANG INT, @NAM INT AS BEGIN SET NOCOUNT ON; SELECT SONGAYCONG, SONGAYNGHI, SOGIOLAMTHEM FROM dbo.BANGCHAMCONG WHERE MANV=@MANV AND THANG=@THANG AND NAM=@NAM; END');

-- BANGLUONG
IF OBJECT_ID('dbo.usp_BangLuong_Insert','P') IS NULL
EXEC('CREATE PROCEDURE dbo.usp_BangLuong_Insert @MALUONG NVARCHAR(8), @LCB MONEY, @PHUCAPCHUCVU MONEY, @PHUCAPKHAC MONEY, @GHICHU NVARCHAR(80) AS BEGIN SET NOCOUNT ON; INSERT INTO dbo.BANGLUONG(MALUONG,LCB,PHUCAPCHUCVU,PHUCAPKHAC,GHICHU) VALUES(@MALUONG,@LCB,@PHUCAPCHUCVU,@PHUCAPKHAC,@GHICHU); END');
IF OBJECT_ID('dbo.usp_BangLuong_Update','P') IS NULL
EXEC('CREATE PROCEDURE dbo.usp_BangLuong_Update @MALUONG NVARCHAR(8), @LCB MONEY, @PHUCAPCHUCVU MONEY, @PHUCAPKHAC MONEY, @GHICHU NVARCHAR(80) AS BEGIN SET NOCOUNT ON; UPDATE dbo.BANGLUONG SET LCB=@LCB, PHUCAPCHUCVU=@PHUCAPCHUCVU, PHUCAPKHAC=@PHUCAPKHAC, GHICHU=@GHICHU WHERE MALUONG=@MALUONG; END');
IF OBJECT_ID('dbo.usp_BangLuong_Delete','P') IS NULL
EXEC('CREATE PROCEDURE dbo.usp_BangLuong_Delete @MALUONG NVARCHAR(8) AS BEGIN SET NOCOUNT ON; DELETE FROM dbo.BANGLUONG WHERE MALUONG=@MALUONG; END');

-- PHONGBAN
IF OBJECT_ID('dbo.usp_PhongBan_Insert','P') IS NULL
EXEC('CREATE PROCEDURE dbo.usp_PhongBan_Insert @MAPHONG NVARCHAR(6), @MABP NVARCHAR(8), @TENPHONG NVARCHAR(20), @NGAYTHANHLAP DATETIME = NULL, @GHICHU NVARCHAR(70) AS BEGIN SET NOCOUNT ON; INSERT INTO dbo.PHONGBAN(MAPHONG,MABP,TENPHONG,NGAYTHANHLAP,GHICHU) VALUES(@MAPHONG,@MABP,@TENPHONG,@NGAYTHANHLAP,@GHICHU); END');
IF OBJECT_ID('dbo.usp_PhongBan_Update','P') IS NULL
EXEC('CREATE PROCEDURE dbo.usp_PhongBan_Update @MAPHONG NVARCHAR(6), @MABP NVARCHAR(8), @TENPHONG NVARCHAR(20), @NGAYTHANHLAP DATETIME = NULL, @GHICHU NVARCHAR(70) AS BEGIN SET NOCOUNT ON; UPDATE dbo.PHONGBAN SET MABP=@MABP, TENPHONG=@TENPHONG, NGAYTHANHLAP=@NGAYTHANHLAP, GHICHU=@GHICHU WHERE MAPHONG=@MAPHONG; END');
IF OBJECT_ID('dbo.usp_PhongBan_Delete','P') IS NULL
EXEC('CREATE PROCEDURE dbo.usp_PhongBan_Delete @MAPHONG NVARCHAR(6) AS BEGIN SET NOCOUNT ON; DELETE FROM dbo.PHONGBAN WHERE MAPHONG=@MAPHONG; END');

-- BOPHAN
IF OBJECT_ID('dbo.usp_BoPhan_Insert','P') IS NULL
EXEC('CREATE PROCEDURE dbo.usp_BoPhan_Insert @MABP NVARCHAR(8), @TENBOPHAN NVARCHAR(20), @NGAYTHANHLAP DATETIME = NULL, @GHICHU NVARCHAR(70) AS BEGIN SET NOCOUNT ON; INSERT INTO dbo.BOPHAN(MABP,TENBOPHAN,NGAYTHANHLAP,GHICHU) VALUES(@MABP,@TENBOPHAN,@NGAYTHANHLAP,@GHICHU); END');
IF OBJECT_ID('dbo.usp_BoPhan_Update','P') IS NULL
EXEC('CREATE PROCEDURE dbo.usp_BoPhan_Update @MABP NVARCHAR(8), @TENBOPHAN NVARCHAR(20), @NGAYTHANHLAP DATETIME = NULL, @GHICHU NVARCHAR(70) AS BEGIN SET NOCOUNT ON; UPDATE dbo.BOPHAN SET TENBOPHAN=@TENBOPHAN, NGAYTHANHLAP=@NGAYTHANHLAP, GHICHU=@GHICHU WHERE MABP=@MABP; END');
IF OBJECT_ID('dbo.usp_BoPhan_Delete','P') IS NULL
EXEC('CREATE PROCEDURE dbo.usp_BoPhan_Delete @MABP NVARCHAR(8) AS BEGIN SET NOCOUNT ON; DELETE FROM dbo.BOPHAN WHERE MABP=@MABP; END');

-- HOSOTHUVIEC
IF OBJECT_ID('dbo.usp_HoSoThuViec_Insert','P') IS NULL
EXEC('CREATE PROCEDURE dbo.usp_HoSoThuViec_Insert @HOTEN NVARCHAR(70), @NGAYSINH DATETIME = NULL, @GIOITINH NVARCHAR(3), @CMND_CCCD NVARCHAR(12), @NOICAP NVARCHAR(20), @VITRITHUVIEC NVARCHAR(25), @NGAYTV DATETIME = NULL, @SOTHANGTV INT, @SDT NVARCHAR(10), @HOCVAN NVARCHAR(20), @GHICHU NVARCHAR(60) AS BEGIN SET NOCOUNT ON; INSERT INTO dbo.HOSOTHUVIEC(HOTEN,NGAYSINH,GIOITINH,CMND_CCCD,NOICAP,VITRITHUVIEC,NGAYTV,SOTHANGTV,SDT,HOCVAN,GHICHU) VALUES(@HOTEN,@NGAYSINH,@GIOITINH,@CMND_CCCD,@NOICAP,@VITRITHUVIEC,@NGAYTV,@SOTHANGTV,@SDT,@HOCVAN,@GHICHU); END');
IF OBJECT_ID('dbo.usp_HoSoThuViec_Update','P') IS NULL
EXEC('CREATE PROCEDURE dbo.usp_HoSoThuViec_Update @MANVTV INT, @HOTEN NVARCHAR(70), @NGAYSINH DATETIME = NULL, @GIOITINH NVARCHAR(3), @CMND_CCCD NVARCHAR(12), @NOICAP NVARCHAR(20), @VITRITHUVIEC NVARCHAR(25), @NGAYTV DATETIME = NULL, @SOTHANGTV INT, @SDT NVARCHAR(10), @HOCVAN NVARCHAR(20), @GHICHU NVARCHAR(60) AS BEGIN SET NOCOUNT ON; UPDATE dbo.HOSOTHUVIEC SET HOTEN=@HOTEN,NGAYSINH=@NGAYSINH,GIOITINH=@GIOITINH,CMND_CCCD=@CMND_CCCD,NOICAP=@NOICAP,VITRITHUVIEC=@VITRITHUVIEC,NGAYTV=@NGAYTV,SOTHANGTV=@SOTHANGTV,SDT=@SDT,HOCVAN=@HOCVAN,GHICHU=@GHICHU WHERE MANVTV=@MANVTV; END');
IF OBJECT_ID('dbo.usp_HoSoThuViec_Delete','P') IS NULL
EXEC('CREATE PROCEDURE dbo.usp_HoSoThuViec_Delete @MANVTV INT AS BEGIN SET NOCOUNT ON; DELETE FROM dbo.HOSOTHUVIEC WHERE MANVTV=@MANVTV; END');
IF OBJECT_ID('dbo.usp_HoSoThuViec_CountByMonthYear','P') IS NULL
EXEC('CREATE PROCEDURE dbo.usp_HoSoThuViec_CountByMonthYear @THANG INT, @NAM INT AS BEGIN SET NOCOUNT ON; SELECT COUNT(1) FROM dbo.HOSOTHUVIEC WHERE MONTH(NGAYTV)=@THANG AND YEAR(NGAYTV)=@NAM; END');

-- NVTHOIVIEC
IF OBJECT_ID('dbo.usp_NVThoiViec_Insert','P') IS NULL
EXEC('CREATE PROCEDURE dbo.usp_NVThoiViec_Insert @MANV INT, @HOTEN NVARCHAR(70), @CMND_CCCD NVARCHAR(12), @NGAYTHOIVIEC DATETIME = NULL, @LYDO NVARCHAR(50) AS BEGIN SET NOCOUNT ON; INSERT INTO dbo.NVTHOIVIEC(MANV,HOTEN,CMND_CCCD,NGAYTHOIVIEC,LYDO) VALUES(@MANV,@HOTEN,@CMND_CCCD,@NGAYTHOIVIEC,@LYDO); END');
IF OBJECT_ID('dbo.usp_NVThoiViec_Update','P') IS NULL
EXEC('CREATE PROCEDURE dbo.usp_NVThoiViec_Update @MANV INT, @HOTEN NVARCHAR(70), @CMND_CCCD NVARCHAR(12), @NGAYTHOIVIEC DATETIME = NULL, @LYDO NVARCHAR(50) AS BEGIN SET NOCOUNT ON; UPDATE dbo.NVTHOIVIEC SET HOTEN=@HOTEN,CMND_CCCD=@CMND_CCCD,NGAYTHOIVIEC=@NGAYTHOIVIEC,LYDO=@LYDO WHERE MANV=@MANV; END');
IF OBJECT_ID('dbo.usp_NVThoiViec_Delete','P') IS NULL
EXEC('CREATE PROCEDURE dbo.usp_NVThoiViec_Delete @MANV INT AS BEGIN SET NOCOUNT ON; DELETE FROM dbo.NVTHOIVIEC WHERE MANV=@MANV; END');
IF OBJECT_ID('dbo.usp_NVThoiViec_CountByMonthYear','P') IS NULL
EXEC('CREATE PROCEDURE dbo.usp_NVThoiViec_CountByMonthYear @THANG INT, @NAM INT AS BEGIN SET NOCOUNT ON; SELECT COUNT(1) FROM dbo.NVTHOIVIEC WHERE MONTH(NGAYTHOIVIEC)=@THANG AND YEAR(NGAYTHOIVIEC)=@NAM; END');

-- THAYDOIBANGLUONG
IF OBJECT_ID('dbo.usp_ThayDoiBangLuong_Insert','P') IS NULL
EXEC('CREATE PROCEDURE dbo.usp_ThayDoiBangLuong_Insert @MANV INT, @MALUONG NVARCHAR(8), @MALUONGMOI NVARCHAR(8), @NGAYSUA DATETIME = NULL, @LYDO NVARCHAR(70) AS BEGIN SET NOCOUNT ON; INSERT INTO dbo.THAYDOIBANGLUONG(MANV,MALUONG,MALUONGMOI,NGAYSUA,LYDO) VALUES(@MANV,@MALUONG,@MALUONGMOI,@NGAYSUA,@LYDO); END');
IF OBJECT_ID('dbo.usp_ThayDoiBangLuong_Update','P') IS NULL
EXEC('CREATE PROCEDURE dbo.usp_ThayDoiBangLuong_Update @MANV INT, @MALUONG NVARCHAR(8), @MALUONGMOI NVARCHAR(8), @NGAYSUA DATETIME = NULL, @LYDO NVARCHAR(70) AS BEGIN SET NOCOUNT ON; UPDATE dbo.THAYDOIBANGLUONG SET NGAYSUA=@NGAYSUA, LYDO=@LYDO WHERE MANV=@MANV AND MALUONG=@MALUONG AND MALUONGMOI=@MALUONGMOI; END');
IF OBJECT_ID('dbo.usp_ThayDoiBangLuong_Delete','P') IS NULL
EXEC('CREATE PROCEDURE dbo.usp_ThayDoiBangLuong_Delete @MANV INT, @MALUONG NVARCHAR(8), @MALUONGMOI NVARCHAR(8) AS BEGIN SET NOCOUNT ON; DELETE FROM dbo.THAYDOIBANGLUONG WHERE MANV=@MANV AND MALUONG=@MALUONG AND MALUONGMOI=@MALUONGMOI; END');
IF OBJECT_ID('dbo.usp_ThayDoiBangLuong_GetByManv','P') IS NULL
EXEC('CREATE PROCEDURE dbo.usp_ThayDoiBangLuong_GetByManv @MANV INT AS BEGIN SET NOCOUNT ON; SELECT * FROM dbo.THAYDOIBANGLUONG WHERE MANV=@MANV; END');

-- NHANVIEN (basic CRUD)
IF OBJECT_ID('dbo.usp_NhanVien_Insert','P') IS NULL
EXEC('CREATE PROCEDURE dbo.usp_NhanVien_Insert @MAPHONG NVARCHAR(6), @MALUONG NVARCHAR(8), @HOTEN NVARCHAR(70), @NGAYSINH DATETIME = NULL, @GIOITINH NVARCHAR(3), @DANTOC NVARCHAR(12), @CMND_CCCD NVARCHAR(12), @NOICAP NVARCHAR(20), @CHUCVU NVARCHAR(25), @MALOAINV NVARCHAR(10), @LOAIHD NVARCHAR(20), @THOIGIAN INT, @NGAYKY DATETIME = NULL, @NGAYHETHAN DATETIME = NULL, @SDT NVARCHAR(10), @HOCVAN NVARCHAR(20), @GHICHU NVARCHAR(60) AS BEGIN SET NOCOUNT ON; INSERT INTO dbo.NHANVIEN(MAPHONG,MALUONG,HOTEN,NGAYSINH,GIOITINH,DANTOC,CMND_CCCD,NOICAP,CHUCVU,MALOAINV,LOAIHD,THOIGIAN,NGAYKY,NGAYHETHAN,SDT,HOCVAN,GHICHU) VALUES(@MAPHONG,@MALUONG,@HOTEN,@NGAYSINH,@GIOITINH,@DANTOC,@CMND_CCCD,@NOICAP,@CHUCVU,@MALOAINV,@LOAIHD,@THOIGIAN,@NGAYKY,@NGAYHETHAN,@SDT,@HOCVAN,@GHICHU); END');
IF OBJECT_ID('dbo.usp_NhanVien_Update','P') IS NULL
EXEC('CREATE PROCEDURE dbo.usp_NhanVien_Update @MANV INT, @MAPHONG NVARCHAR(6), @MALUONG NVARCHAR(8), @HOTEN NVARCHAR(70), @NGAYSINH DATETIME = NULL, @GIOITINH NVARCHAR(3), @DANTOC NVARCHAR(12), @CMND_CCCD NVARCHAR(12), @NOICAP NVARCHAR(20), @CHUCVU NVARCHAR(25), @MALOAINV NVARCHAR(10), @LOAIHD NVARCHAR(20), @THOIGIAN INT, @NGAYKY DATETIME = NULL, @NGAYHETHAN DATETIME = NULL, @SDT NVARCHAR(10), @HOCVAN NVARCHAR(20), @GHICHU NVARCHAR(60) AS BEGIN SET NOCOUNT ON; UPDATE dbo.NHANVIEN SET MAPHONG=@MAPHONG, MALUONG=@MALUONG, HOTEN=@HOTEN, NGAYSINH=@NGAYSINH, GIOITINH=@GIOITINH, DANTOC=@DANTOC, CMND_CCCD=@CMND_CCCD, NOICAP=@NOICAP, CHUCVU=@CHUCVU, MALOAINV=@MALOAINV, LOAIHD=@LOAIHD, THOIGIAN=@THOIGIAN, NGAYKY=@NGAYKY, NGAYHETHAN=@NGAYHETHAN, SDT=@SDT, HOCVAN=@HOCVAN, GHICHU=@GHICHU WHERE MANV=@MANV; END');
IF OBJECT_ID('dbo.usp_NhanVien_Delete','P') IS NULL
EXEC('CREATE PROCEDURE dbo.usp_NhanVien_Delete @MANV INT AS BEGIN SET NOCOUNT ON; DELETE FROM dbo.NHANVIEN WHERE MANV=@MANV; END');

-- SOTHAISAN
IF OBJECT_ID('dbo.usp_SoThaiSan_Insert','P') IS NULL
EXEC('CREATE PROCEDURE dbo.usp_SoThaiSan_Insert @MANV INT, @NGAYVESOM DATETIME = NULL, @NGAYNGHISINH DATETIME = NULL, @NGAYLAMTROLAI DATETIME = NULL, @TROCAPCTY MONEY, @GHICHU NVARCHAR(70) AS BEGIN SET NOCOUNT ON; INSERT INTO dbo.SOTHAISAN(MANV,NGAYVESOM,NGAYNGHISINH,NGAYLAMTROLAI,TROCAPCTY,GHICHU) VALUES(@MANV,@NGAYVESOM,@NGAYNGHISINH,@NGAYLAMTROLAI,@TROCAPCTY,@GHICHU); END');
IF OBJECT_ID('dbo.usp_SoThaiSan_Update','P') IS NULL
EXEC('CREATE PROCEDURE dbo.usp_SoThaiSan_Update @MATS INT, @MANV INT, @NGAYVESOM DATETIME = NULL, @NGAYNGHISINH DATETIME = NULL, @NGAYLAMTROLAI DATETIME = NULL, @TROCAPCTY MONEY, @GHICHU NVARCHAR(70) AS BEGIN SET NOCOUNT ON; UPDATE dbo.SOTHAISAN SET MANV=@MANV, NGAYVESOM=@NGAYVESOM, NGAYNGHISINH=@NGAYNGHISINH, NGAYLAMTROLAI=@NGAYLAMTROLAI, TROCAPCTY=@TROCAPCTY, GHICHU=@GHICHU WHERE MATS=@MATS; END');
IF OBJECT_ID('dbo.usp_SoThaiSan_Delete','P') IS NULL
EXEC('CREATE PROCEDURE dbo.usp_SoThaiSan_Delete @MATS INT AS BEGIN SET NOCOUNT ON; DELETE FROM dbo.SOTHAISAN WHERE MATS=@MATS; END');

-- KHENTHUONG
IF OBJECT_ID('dbo.usp_KhenThuong_Insert','P') IS NULL
EXEC('CREATE PROCEDURE dbo.usp_KhenThuong_Insert @TIEN MONEY, @LYDO NVARCHAR(50) AS BEGIN SET NOCOUNT ON; INSERT INTO dbo.KHENTHUONG(TIEN,LYDO) VALUES(@TIEN,@LYDO); END');
IF OBJECT_ID('dbo.usp_KhenThuong_Update','P') IS NULL
EXEC('CREATE PROCEDURE dbo.usp_KhenThuong_Update @MAKT INT, @TIEN MONEY, @LYDO NVARCHAR(50) AS BEGIN SET NOCOUNT ON; UPDATE dbo.KHENTHUONG SET TIEN=@TIEN, LYDO=@LYDO WHERE MAKT=@MAKT; END');
IF OBJECT_ID('dbo.usp_KhenThuong_Delete','P') IS NULL
EXEC('CREATE PROCEDURE dbo.usp_KhenThuong_Delete @MAKT INT AS BEGIN SET NOCOUNT ON; DELETE FROM dbo.KHENTHUONG WHERE MAKT=@MAKT; END');

PRINT 'Stored procedures for main tables created (dbo.usp_...). Modify DAL to call these stored procedures.';
-- BAOCAOLUONG procs
IF OBJECT_ID('dbo.usp_BaoCaoLuong_GetAll','P') IS NULL
EXEC('CREATE PROCEDURE dbo.usp_BaoCaoLuong_GetAll AS BEGIN SET NOCOUNT ON; SELECT * FROM dbo.BAOCAOLUONG; END');
IF OBJECT_ID('dbo.usp_BaoCaoLuong_Insert','P') IS NULL
EXEC('CREATE PROCEDURE dbo.usp_BaoCaoLuong_Insert @THANG INT, @NAM INT, @GHICHU NVARCHAR(50) AS BEGIN SET NOCOUNT ON; INSERT INTO dbo.BAOCAOLUONG(THANG,NAM,GHICHU) VALUES(@THANG,@NAM,@GHICHU); END');
IF OBJECT_ID('dbo.usp_BaoCaoLuong_Update','P') IS NULL
EXEC('CREATE PROCEDURE dbo.usp_BaoCaoLuong_Update @THANG INT, @NAM INT, @GHICHU NVARCHAR(50) AS BEGIN SET NOCOUNT ON; UPDATE dbo.BAOCAOLUONG SET GHICHU=@GHICHU WHERE THANG=@THANG AND NAM=@NAM; END');
IF OBJECT_ID('dbo.usp_BaoCaoLuong_Delete','P') IS NULL
EXEC('CREATE PROCEDURE dbo.usp_BaoCaoLuong_Delete @THANG INT, @NAM INT AS BEGIN SET NOCOUNT ON; DELETE FROM dbo.BAOCAOLUONG WHERE THANG=@THANG AND NAM=@NAM; END');
-- GetAll procedures
IF OBJECT_ID('dbo.usp_BangTinhLuong_GetAll','P') IS NULL
EXEC('CREATE PROCEDURE dbo.usp_BangTinhLuong_GetAll AS BEGIN SET NOCOUNT ON; SELECT * FROM dbo.BANGTINHLUONG; END');
IF OBJECT_ID('dbo.usp_BangChamCong_GetAll','P') IS NULL
EXEC('CREATE PROCEDURE dbo.usp_BangChamCong_GetAll AS BEGIN SET NOCOUNT ON; SELECT B.*, N.HOTEN FROM dbo.BANGCHAMCONG B LEFT JOIN dbo.NHANVIEN N ON B.MANV = N.MANV; END');
IF OBJECT_ID('dbo.usp_BangLuong_GetAll','P') IS NULL
EXEC('CREATE PROCEDURE dbo.usp_BangLuong_GetAll AS BEGIN SET NOCOUNT ON; SELECT * FROM dbo.BANGLUONG; END');
IF OBJECT_ID('dbo.usp_PhongBan_GetAll','P') IS NULL
EXEC('CREATE PROCEDURE dbo.usp_PhongBan_GetAll AS BEGIN SET NOCOUNT ON; SELECT * FROM dbo.PHONGBAN; END');
IF OBJECT_ID('dbo.usp_BoPhan_GetAll','P') IS NULL
EXEC('CREATE PROCEDURE dbo.usp_BoPhan_GetAll AS BEGIN SET NOCOUNT ON; SELECT * FROM dbo.BOPHAN; END');
IF OBJECT_ID('dbo.usp_HoSoThuViec_GetAll','P') IS NULL
EXEC('CREATE PROCEDURE dbo.usp_HoSoThuViec_GetAll AS BEGIN SET NOCOUNT ON; SELECT * FROM dbo.HOSOTHUVIEC; END');
IF OBJECT_ID('dbo.usp_NVThoiViec_GetAll','P') IS NULL
EXEC('CREATE PROCEDURE dbo.usp_NVThoiViec_GetAll AS BEGIN SET NOCOUNT ON; SELECT * FROM dbo.NVTHOIVIEC; END');
IF OBJECT_ID('dbo.usp_ThayDoiBangLuong_GetAll','P') IS NULL
EXEC('CREATE PROCEDURE dbo.usp_ThayDoiBangLuong_GetAll AS BEGIN SET NOCOUNT ON; SELECT * FROM dbo.THAYDOIBANGLUONG; END');
IF OBJECT_ID('dbo.usp_NhanVien_GetAll','P') IS NULL
EXEC('CREATE PROCEDURE dbo.usp_NhanVien_GetAll AS BEGIN SET NOCOUNT ON; SELECT * FROM dbo.NHANVIEN; END');
IF OBJECT_ID('dbo.usp_SoThaiSan_GetAll','P') IS NULL
EXEC('CREATE PROCEDURE dbo.usp_SoThaiSan_GetAll AS BEGIN SET NOCOUNT ON; SELECT * FROM dbo.SOTHAISAN; END');
IF OBJECT_ID('dbo.usp_KhenThuong_GetAll','P') IS NULL
EXEC('CREATE PROCEDURE dbo.usp_KhenThuong_GetAll AS BEGIN SET NOCOUNT ON; SELECT * FROM dbo.KHENTHUONG; END');
-- NhanVien search by maphong and name (uses fChuyenCoDauThanhKhongDau for name normalization)
IF OBJECT_ID('dbo.usp_NhanVien_Search','P') IS NULL
EXEC('CREATE PROCEDURE dbo.usp_NhanVien_Search @MAPHONG NVARCHAR(6) = NULL, @TEN NVARCHAR(200) = NULL AS BEGIN SET NOCOUNT ON; IF (@MAPHONG IS NULL OR @MAPHONG='''') AND (@TEN IS NULL OR @TEN='''') BEGIN SELECT * FROM dbo.NHANVIEN; RETURN; END; IF (@MAPHONG IS NULL OR @MAPHONG='''') BEGIN SELECT * FROM dbo.NHANVIEN WHERE dbo.fChuyenCoDauThanhKhongDau(HOTEN) LIKE @TEN; RETURN; END; IF (@TEN IS NULL OR @TEN='''') BEGIN SELECT * FROM dbo.NHANVIEN WHERE MAPHONG = @MAPHONG; RETURN; END; SELECT * FROM dbo.NHANVIEN WHERE MAPHONG = @MAPHONG AND dbo.fChuyenCoDauThanhKhongDau(HOTEN) LIKE @TEN; END');

IF OBJECT_ID('dbo.usp_NhanVien_GetNameById','P') IS NULL
EXEC('CREATE PROCEDURE dbo.usp_NhanVien_GetNameById @MANV INT AS BEGIN SET NOCOUNT ON; SELECT HOTEN FROM dbo.NHANVIEN WHERE MANV = @MANV; END');
