-- Create AuditLog table and stored procedures for user/role operations
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[AuditLog]') AND type in (N'U'))
BEGIN
	CREATE TABLE dbo.AuditLog
	(
		Id INT IDENTITY(1,1) PRIMARY KEY,
		EventTime DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
		EventType NVARCHAR(100) NOT NULL,
		Username NVARCHAR(200) NULL,
		Target NVARCHAR(200) NULL,
		Details NVARCHAR(MAX) NULL,
		UserId INT NULL,
		Status NVARCHAR(50) NULL
	);
END

GO

-- Stored procedure to write audit
IF OBJECT_ID('dbo.usp_AuditLog_Add','P') IS NULL
EXEC('CREATE PROCEDURE dbo.usp_AuditLog_Add @EventType NVARCHAR(100), @Username NVARCHAR(200), @Target NVARCHAR(200), @Details NVARCHAR(MAX), @UserId INT = NULL, @Status NVARCHAR(50) = NULL AS BEGIN SET NOCOUNT ON; INSERT INTO dbo.AuditLog(EventType, Username, Target, Details, UserId, Status) VALUES(@EventType, @Username, @Target, @Details, @UserId, @Status); END');

GO

-- Example: stored procedures for user operations (insert/update/delete)
IF OBJECT_ID('dbo.usp_User_Create','P') IS NULL
EXEC('CREATE PROCEDURE dbo.usp_User_Create @MALOAITK INT, @TENCHU NVARCHAR(200), @TENDANGNHAP NVARCHAR(200), @MATKHAU NVARCHAR(MAX) AS BEGIN SET NOCOUNT ON; INSERT INTO TAIKHOAN(MALOAITK,TENCHUTAIKHOAN,TENDANGNHAP,MATKHAU) VALUES(@MALOAITK,@TENCHU,@TENDANGNHAP,@MATKHAU); EXEC dbo.usp_AuditLog_Add ''UserCreate'', @TENDANGNHAP, NULL, ''User created'', NULL, ''Success''; END');

GO

IF OBJECT_ID('dbo.usp_User_Update','P') IS NULL
EXEC('CREATE PROCEDURE dbo.usp_User_Update @MATK INT, @MALOAITK INT, @TENCHU NVARCHAR(200), @TENDANGNHAP NVARCHAR(200), @MATKHAU NVARCHAR(MAX) AS BEGIN SET NOCOUNT ON; UPDATE TAIKHOAN SET MALOAITK=@MALOAITK, TENCHUTAIKHOAN=@TENCHU, TENDANGNHAP=@TENDANGNHAP, MATKHAU=@MATKHAU WHERE MATK=@MATK; EXEC dbo.usp_AuditLog_Add ''UserUpdate'', @TENDANGNHAP, NULL, ''User updated'', @MATK, ''Success''; END');

GO

IF OBJECT_ID('dbo.usp_User_Delete','P') IS NULL
EXEC('CREATE PROCEDURE dbo.usp_User_Delete @MATK INT AS BEGIN SET NOCOUNT ON; DECLARE @t NVARCHAR(200); SELECT @t = TENDANGNHAP FROM TAIKHOAN WHERE MATK=@MATK; DELETE FROM TAIKHOAN WHERE MATK=@MATK; EXEC dbo.usp_AuditLog_Add ''UserDelete'', @t, NULL, ''User deleted'', @MATK, ''Success''; END');

GO

-- Role table and stored procs if not exist
IF OBJECT_ID('dbo.PHANLOAITAIKHOAN','U') IS NULL
BEGIN
CREATE TABLE dbo.PHANLOAITAIKHOAN(MALOAITK INT IDENTITY(1,1) PRIMARY KEY, TENLOAITAIKHOAN NVARCHAR(200), QUYENHAN NVARCHAR(MAX));
END

GO

IF OBJECT_ID('dbo.usp_Role_Create','P') IS NULL
EXEC('CREATE PROCEDURE dbo.usp_Role_Create @TENLOAI NVARCHAR(200), @QUYEN NVARCHAR(MAX) AS BEGIN SET NOCOUNT ON; INSERT INTO PHANLOAITAIKHOAN(TENLOAITAIKHOAN,QUYENHAN) VALUES(@TENLOAI,@QUYEN); EXEC dbo.usp_AuditLog_Add ''RoleCreate'', NULL, @TENLOAI, ''Role created'', NULL, ''Success''; END');

GO

IF OBJECT_ID('dbo.usp_Role_Update','P') IS NULL
EXEC('CREATE PROCEDURE dbo.usp_Role_Update @MALOAITK INT, @TENLOAI NVARCHAR(200), @QUYEN NVARCHAR(MAX) AS BEGIN SET NOCOUNT ON; UPDATE PHANLOAITAIKHOAN SET TENLOAITAIKHOAN=@TENLOAI, QUYENHAN=@QUYEN WHERE MALOAITK=@MALOAITK; EXEC dbo.usp_AuditLog_Add ''RoleUpdate'', NULL, @TENLOAI, ''Role updated'', @MALOAITK, ''Success''; END');

GO

IF OBJECT_ID('dbo.usp_Role_Delete','P') IS NULL
EXEC('CREATE PROCEDURE dbo.usp_Role_Delete @MALOAITK INT AS BEGIN SET NOCOUNT ON; DECLARE @t NVARCHAR(200); SELECT @t = TENLOAITAIKHOAN FROM PHANLOAITAIKHOAN WHERE MALOAITK=@MALOAITK; DELETE FROM PHANLOAITAIKHOAN WHERE MALOAITK=@MALOAITK; EXEC dbo.usp_AuditLog_Add ''RoleDelete'', NULL, @t, ''Role deleted'', @MALOAITK, ''Success''; END');

GO

-- UserRole mapping table
IF OBJECT_ID('dbo.USER_ROLE','U') IS NULL
BEGIN
	CREATE TABLE dbo.USER_ROLE (MATK INT NOT NULL, MALOAITK INT NOT NULL, CONSTRAINT FK_USER_ROLE_USER FOREIGN KEY (MATK) REFERENCES TAIKHOAN(MATK), CONSTRAINT FK_USER_ROLE_ROLE FOREIGN KEY (MALOAITK) REFERENCES PHANLOAITAIKHOAN(MALOAITK));
END

GO

IF OBJECT_ID('dbo.usp_UserRole_Assign','P') IS NULL
EXEC('CREATE PROCEDURE dbo.usp_UserRole_Assign @MATK INT, @MALOAITK INT AS BEGIN SET NOCOUNT ON; IF NOT EXISTS(SELECT 1 FROM USER_ROLE WHERE MATK=@MATK AND MALOAITK=@MALOAITK) INSERT INTO USER_ROLE(MATK,MALOAITK) VALUES(@MATK,@MALOAITK); EXEC dbo.usp_AuditLog_Add ''UserRoleAssign'', NULL, CAST(@MATK AS NVARCHAR(50)), CAST(@MALOAITK AS NVARCHAR(50)), @MATK, ''Success''; END');

GO

IF OBJECT_ID('dbo.usp_UserRole_Revoke','P') IS NULL
EXEC('CREATE PROCEDURE dbo.usp_UserRole_Revoke @MATK INT, @MALOAITK INT AS BEGIN SET NOCOUNT ON; DELETE FROM USER_ROLE WHERE MATK=@MATK AND MALOAITK=@MALOAITK; EXEC dbo.usp_AuditLog_Add ''UserRoleRevoke'', NULL, CAST(@MATK AS NVARCHAR(50)), CAST(@MALOAITK AS NVARCHAR(50)), @MATK, ''Success''; END');

-- Add account lockout columns to TAIKHOAN if missing
IF COL_LENGTH('dbo.TAIKHOAN','FailedLoginCount') IS NULL
BEGIN
	ALTER TABLE dbo.TAIKHOAN ADD FailedLoginCount INT NOT NULL DEFAULT(0);
END
IF COL_LENGTH('dbo.TAIKHOAN','LockoutUntil') IS NULL
BEGIN
	ALTER TABLE dbo.TAIKHOAN ADD LockoutUntil DATETIME2 NULL;
END

-- Add configurable lockout settings in THAMSO
IF OBJECT_ID('dbo.THAMSO','U') IS NOT NULL
BEGIN
	IF NOT EXISTS(SELECT 1 FROM THAMSO WHERE MATHAMSO='TS06') INSERT INTO THAMSO(MATHAMSO, TENTHAMSO, GIATRI) VALUES('TS06','LockoutThreshold','5');
	IF NOT EXISTS(SELECT 1 FROM THAMSO WHERE MATHAMSO='TS07') INSERT INTO THAMSO(MATHAMSO, TENTHAMSO, GIATRI) VALUES('TS07','LockoutMinutes','15');
END

-- Stored procedure to unlock a user account manually
IF OBJECT_ID('dbo.usp_User_Unlock','P') IS NULL
EXEC('CREATE PROCEDURE dbo.usp_User_Unlock @MATK INT AS BEGIN SET NOCOUNT ON; UPDATE TAIKHOAN SET FailedLoginCount = 0, LockoutUntil = NULL WHERE MATK = @MATK; EXEC dbo.usp_AuditLog_Add ''UserUnlock'', NULL, CAST(@MATK AS NVARCHAR(50)), ''Account unlocked'', @MATK, ''Success''; END');

GO
