-- DBScripts/init_security.sql
-- Only DDL and configuration; stored procedures are in DBScripts/StoredProcedures/*.sql

-- Create AuditLog table if missing
IF NOT EXISTS (SELECT 1 FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[AuditLog]') AND type = N'U')
BEGIN
    CREATE TABLE dbo.AuditLog
    (
        Id INT IDENTITY(1,1) PRIMARY KEY,
        EventTime DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
        EventType NVARCHAR(100) NOT NULL,
        Username NVARCHAR(200) NULL,
        Target NVARCHAR(200) NULL,
        Details NVARCHAR(MAX) NULL,
        UserId INT NULL,
        Status NVARCHAR(50) NULL
    );
END

-- Ensure role table exists with expected columns
IF OBJECT_ID('dbo.PHANLOAITAIKHOAN','U') IS NULL
BEGIN
    CREATE TABLE dbo.PHANLOAITAIKHOAN
    (
        MALOAITK INT IDENTITY(1,1) PRIMARY KEY,
        TENLOAITAIKHOAN NVARCHAR(200) NULL,
        QUYENHAN NVARCHAR(MAX) NULL
    );
END
ELSE
BEGIN
    IF COL_LENGTH('dbo.PHANLOAITAIKHOAN','TENLOAITAIKHOAN') IS NULL
        ALTER TABLE dbo.PHANLOAITAIKHOAN ADD TENLOAITAIKHOAN NVARCHAR(200) NULL;
    IF COL_LENGTH('dbo.PHANLOAITAIKHOAN','QUYENHAN') IS NULL
        ALTER TABLE dbo.PHANLOAITAIKHOAN ADD QUYENHAN NVARCHAR(MAX) NULL;
END

-- UserRole mapping table
IF OBJECT_ID('dbo.USER_ROLE','U') IS NULL
BEGIN
    CREATE TABLE dbo.USER_ROLE
    (
        MATK INT NOT NULL,
        MALOAITK INT NOT NULL,
        CONSTRAINT FK_USER_ROLE_USER FOREIGN KEY (MATK) REFERENCES TAIKHOAN(MATK),
        CONSTRAINT FK_USER_ROLE_ROLE FOREIGN KEY (MALOAITK) REFERENCES PHANLOAITAIKHOAN(MALOAITK)
    );
END

-- Add account lockout columns to TAIKHOAN if missing
IF OBJECT_ID('dbo.TAIKHOAN','U') IS NOT NULL
BEGIN
    IF COL_LENGTH('dbo.TAIKHOAN','FailedLoginCount') IS NULL
        ALTER TABLE dbo.TAIKHOAN ADD FailedLoginCount INT NOT NULL CONSTRAINT DF_TAIKHOAN_FailedLoginCount DEFAULT (0);
    IF COL_LENGTH('dbo.TAIKHOAN','LockoutUntil') IS NULL
        ALTER TABLE dbo.TAIKHOAN ADD LockoutUntil DATETIME2 NULL;
END

-- Add configurable lockout settings in THAMSO
IF OBJECT_ID('dbo.THAMSO','U') IS NOT NULL
BEGIN
    IF NOT EXISTS(SELECT 1 FROM THAMSO WHERE MATHAMSO='TS06')
        INSERT INTO THAMSO(MATHAMSO, TENTHAMSO, GIATRI) VALUES('TS06','LockoutThreshold','5');
    IF NOT EXISTS(SELECT 1 FROM THAMSO WHERE MATHAMSO='TS07')
        INSERT INTO THAMSO(MATHAMSO, TENTHAMSO, GIATRI) VALUES('TS07','LockoutMinutes','15');
END